services:
  web:
    build: .
    ports:
      - "8080:80"
      - "3030:3030"
    volumes:
      - .:/var/www/html
    command: bash -c "apache2-foreground & php ./src/Server.php"
    networks:
      - webnet

networks:
  webnet:
    driver: bridge
